name: Tom Reeves
favicon: null
layout_spectrum: 0.21769
typography_spectrum: 0.9606332264374942
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0040a2'
    - '#eeeae7'
    - '#0080e1'
    - '#000200'
    - '#86a8c4'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0.25
  rhythmicContrast: 0.35813297773711383
purpose: []
