name: Tom Reeves
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9606332264374942
title: Tom Reeves Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#e9e9e9'
    - '#444444'
    - '#a3a3a3'
    - '#02327c'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
